### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [mkmer/AIOAladdinConnect#2]
It would be very helpful if you could tag releases again (0.1.20 was the last one). This would enable distributions to fetch the package from GitHub instead of Pypi if they want.

Thanks

**Comment by mkmer** [comment]
I may not understand your statement (still relatively new to the process). There are tags on the source for each release... is there some other "tag" you are asking for?

**Comment by mkmer** [comment]
OK.. I somehow release 0.1.21 to pypi without a tag.  Sorry - should be good now.
